kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "spring-boot-caj-app.fullname" . }}
  labels:
    app: "{{ template "spring-boot-caj-app.fullname" . }}"
    version: "{{ .Values.version }}"
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: "{{ template "spring-boot-caj-app.fullname" . }}"
      version: "{{ .Values.version }}"
  template:
    metadata:
      labels:
        app: "{{ template "spring-boot-caj-app.fullname" . }}"
        version: "{{ .Values.version }}"
    spec:
      containers:
        - name: "{{ template "spring-boot-caj-app.fullname" . }}"
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: MASTER_FILE_URI	
            value: 'http://caj-master-file:8080'	
          - name: FARE_URI	
            value: 'http://caj-fare:8080'	
          - name: SCHEDULE_URI	
            value: 'http://caj-schedule:8080'
          ports:
          - containerPort: 8080
            protocol: TCP
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
